apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: san-ingress
  namespace: san
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  ingressClassName: nginx
  rules:
    - host: api.san.local
      http:
        paths:
          - path: /(auth.*)
            pathType: Prefix
            backend:
              service:
                name: gateway
                port:
                  number: 8080
          - path: /(patients.*)
            pathType: Prefix
            backend:
              service:
                name: gateway
                port:
                  number: 8080
          - path: /(appointments.*)
            pathType: Prefix
            backend:
              service:
                name: gateway
                port:
                  number: 8080
    - host: app.san.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 5173


